# Generated by Django 5.1.3 on 2024-11-20 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('cedula', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del cliente : ')),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('direccion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('Fecha_nacimiento', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Cliente :',
                'verbose_name_plural': 'Clientes',
                'db_table': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('cedula', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='Cedula del Empleado :')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del Empleado : ')),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('direccion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_nacimiento', models.DateField()),
            ],
            options={
                'verbose_name': 'Empleado :',
                'verbose_name_plural': 'Empleados',
                'db_table': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('ruc', models.CharField(max_length=13, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de la empresa : ')),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'verbose_name': 'Empresa :',
                'verbose_name_plural': 'Empresas',
                'db_table': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50, verbose_name=' Nombre del producto : ')),
                ('marca', models.CharField(max_length=50, unique=True)),
                ('caracteristicas_categoria', models.CharField(choices=[('Bebidas', 'Bebidas'), ('Comidas', 'Comidas'), ('Limpieza', 'Limpieza'), ('Ropa', 'Ropa'), ('Varios', 'Varios')], max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio del producto : ')),
                ('cantidad_stock', models.IntegerField(verbose_name='Cantidad en stock : ')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fecha_elaboracion', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
            ],
            options={
                'verbose_name': 'Producto :',
                'verbose_name_plural': 'Productos',
                'db_table': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('codigo_factura', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_factura', models.DateTimeField(auto_now_add=True)),
                ('cantidad', models.IntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ventasapp.clientes')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ventasapp.empleados')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ventasapp.productos')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'db_table': 'Facturas',
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('cedula', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del proveedor : ')),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ventasapp.empresas')),
            ],
            options={
                'verbose_name': 'Proveedor ',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'Proveedores',
            },
        ),
    ]
