# Generated by Django 5.1.3 on 2024-11-23 04:15

import Ventasapp.validadores
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventasapp', '0003_alter_clientes_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='cantidad_original',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientes',
            name='direccion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='cedula',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Cedula del Empleado :'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productos',
            name='caracteristicas_categoria',
            field=models.CharField(choices=[('Bebidas', 'Bebidas'), ('Comidas', 'Comidas'), ('Limpieza', 'Limpieza'), ('Ropa', 'Ropa'), ('Varios', 'Varios')], max_length=100),
        ),
        migrations.AlterField(
            model_name='productos',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name=' Nombre del producto  '),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precio',
            field=models.DecimalField(decimal_places=2, help_text='ingresa valores con decimales', max_digits=10, verbose_name='Precio del producto : '),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='cedula',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinLengthValidator(10), Ventasapp.validadores.validacion_numeros]),
        ),
    ]
