# Generated by Django 5.1.3 on 2024-11-23 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventasapp', '0004_factura_cantidad_original_alter_clientes_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='cantidad_original',
            field=models.IntegerField(blank=True),
        ),
    ]
