# Generated by Django 5.1.3 on 2024-12-05 13:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventasapp', '0007_factura_estados'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Tarjeta de Crédito', 'Tarjeta de Crédito'), ('Transferencia Bancaria', 'Transferencia Bancaria')], max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Método de Pago',
                'verbose_name_plural': 'Métodos de Pago',
            },
        ),
        migrations.AlterModelOptions(
            name='clientes',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.RenameField(
            model_name='clientes',
            old_name='Fecha_nacimiento',
            new_name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='estados',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='iva',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='total',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='caracteristicas_categoria',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='fecha_ingreso',
        ),
        migrations.AddField(
            model_name='productos',
            name='categoria',
            field=models.CharField(choices=[('Bebidas', 'Bebidas'), ('Comidas', 'Comidas'), ('Limpieza', 'Limpieza'), ('Ropa', 'Ropa'), ('Varios', 'Varios')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cedula',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='productos',
            name='cantidad_stock',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='productos',
            name='marca',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='productos',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterModelTable(
            name='clientes',
            table=None,
        ),
        migrations.AlterModelTable(
            name='factura',
            table=None,
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('iva', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('estados', models.CharField(choices=[('V', 'Vendida'), ('A', 'Anulada')], max_length=40)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ventasapp.factura')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ventasapp.productos')),
            ],
            options={
                'verbose_name': 'Detalle Factura',
                'verbose_name_plural': 'Detalles Facturas',
                'db_table': 'DetallesFacturas',
            },
        ),
        migrations.AddField(
            model_name='factura',
            name='metodo_pago',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ventasapp.metodopago'),
        ),
    ]
