# Generated by Django 5.1.3 on 2024-12-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventasapp', '0008_metodopago_alter_clientes_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallefactura',
            name='iva',
        ),
        migrations.RemoveField(
            model_name='detallefactura',
            name='total',
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='factura',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='factura',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='factura',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
    ]
